[build]
compiler = "gcc"

[[targets]]
name = "main"
src = "./src/"
include_dir = "./src/include/"
type = "exe"
cflags = "-g `llvm-config --cflags`"
libs = "`llvm-config --libs core` `llvm-config --ldflags --system-libs`"
deps = [""]
